### ISSUE TITLE
Obsolete .net version

### ISSUE THREAD

**Issue by solarisfire** [Sh0ckFR/Starfield-Game-WideScreen-Patcher#1]
Windows won't actually let me install one old enough to run this...

![image](https://github.com/Sh0ckFR/Starfield-Game-WideScreen-Patcher/assets/420952/ac6491da-9434-4047-9530-59f2a5455f2e)

**Comment by Sh0ckFR** [comment]
Can you try to redownload it and retry? I replaced the binaries recently, it should work, if it doesn't work, please let me know.

**Comment by solarisfire** [comment]
That works!
